name: Debian Build
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - run: sudo apt-get update
      - run: sudo apt-get install -y build-essential devscripts equivs
      - run: sudo mk-build-deps -i -r
      - run: dpkg-buildpackage -us -uc -b
      - uses: actions/upload-artifact@v7
        with:
          name: deb-package
          path: ../alpha_*.deb
