name: Flatpak Build
on: [push, workflow_dispatch]

jobs:
  flatpak:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-50
      options: --privileged
    steps:
      - uses: actions/checkout@v7
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          manifest-path: io.github.d3msudo.clamguard.json
          cache-key: flatpak-builder-${{ github.sha }}
